FROM ubuntu

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \ 
    && apt-get install -y --no-install-recommends \
        gpg \
        gpg-agent \
        software-properties-common \
    && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php \
    && apt-get update \ 
    && apt-get install -y --no-install-recommends \
        git \
        curl \
        make \
        php8.3 \
        php8.3-cli \
        php8.3-curl \
        php8.3-intl \
        php8.3-gd \
        php8.3-mbstring \
        php8.3-mysql \
        php8.3-opcache \
        php8.3-sqlite3 \
        php8.3-xdebug \
        php8.3-xml \
        php8.3-zip \
    && rm -rf /var/lib/apt/lists/*

RUN git config --global user.email "you@example.com" \
    && git config --global user.name "Your Name"

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

WORKDIR /build/symfony
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony \
    && rm -f /tmp/*

WORKDIR /home/dbw
CMD ["php", "-S", "localhost:80"]
