FROM ubuntu

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \ 
    && apt-get install -y --no-install-recommends \
        gpg \
        gpg-agent \
        software-properties-common \
    && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php \
    && apt-get update \ 
    && apt-get install -y --no-install-recommends \
        git \
        curl \
        make \
        php8.4 \
        php8.4-cli \
        php8.4-curl \
        php8.4-intl \
        php8.4-gd \
        php8.4-mbstring \
        php8.4-mysql \
        php8.4-opcache \
        php8.4-sqlite3 \
        php8.4-xdebug \
        php8.4-xml \
        php8.4-zip \
        rsync \
        sqlite3 \
        unzip \
        wget \
        zip \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        nodejs  \
    && rm -rf /var/lib/apt/lists/*

RUN git config --global user.email "you@example.com" \
    && git config --global user.name "Your Name"

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

WORKDIR /build/symfony
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony \
    && rm -f /tmp/*

# # Act as local user, not root, with workdir homedir
# RUN groupadd -r dbw && useradd --no-log-init -r -g dbw dbw
# WORKDIR /home/dbw
# USER dbw

#EXPOSE 8888

# Act as local user, not root, with workdir homedir
ARG localUser=dbw
ARG workdir=/home/$localUser
RUN useradd --create-home --shell /bin/bash $localUser \
	&& mkdir -p $workdir \
	&& chown $localUser $workdir
USER $localUser
WORKDIR $workdir
